name: Docker

on:
  push:
    branches:
      - master
    paths:
      - '**/VERSION'
jobs:
  publish-docker-hub:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login ${{ secrets.DOCKER_REGISTRY_URL }} -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and push the images
        run: |
          for versionFilePath in $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} ${{ github.event.before }} | grep "VERSION");
          do
            folder=${versionFilePath%"/VERSION"}
            IMAGE_NAME=${folder##*/}

            VERSION=$(cat $versionFilePath)
            IMAGE_ID=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME
            docker build $folder --file $folder/Dockerfile --tag $IMAGE_ID
            docker tag $IMAGE_ID $IMAGE_ID:$VERSION

            echo IMAGE_ID=$IMAGE_ID

            docker push $IMAGE_ID:$VERSION
            docker push $IMAGE_ID
          done;
